### PR TITLE
Number of context lines vs. common threshold 

### PR DESCRIPTION
**Pull request by SpacePossum**
Under some conditions to many context lines where generated.
This is still raw and needs more testing (and documentation :|  )
 
Note to self, tree shake this first

### CODE REVIEW

**Comment by SpacePossum** [comment]
if this passes;
- the OutputBuilder here get patched
- the PR here https://github.com/sebastianbergmann/diff/pull/75 gets fixed
- this whole package get PR'ed to https://github.com/sebastianbergmann/diff
- this package gets deleted

**Comment by keradus** [comment]
> this package gets deleted

wow, no more udiff ?

**Comment by SpacePossum** [comment]
This will go if all of what is in here gets merge into `sebastianbergmann/diff`, if that merge fails than this will stay where it is, no worries!

**Comment by keradus** [comment]
in any case, please don't delete the repo, just mark it as archived, so package that is relying on it will not crash...

**Pull request merged**
